// <auto-generated />
using System;
using DissCouncil.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DissCouncil.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727074115_AddDefense")]
    partial class AddDefense
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DissCouncil.Domain.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("DissCouncil.Domain.Entities.Defense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CouncilMembersPresent")
                        .HasColumnType("integer");

                    b.Property<int>("CouncilMembersRequired")
                        .HasColumnType("integer");

                    b.Property<Guid>("DissertationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvalidBallots")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotesAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("VotesFor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DissertationId");

                    b.ToTable("Defenses");
                });

            modelBuilder.Entity("DissCouncil.Domain.Entities.Dissertation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<string>("SpecialtyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("Dissertations");
                });

            modelBuilder.Entity("DissCouncil.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DissCouncil.Domain.Entities.Defense", b =>
                {
                    b.HasOne("DissCouncil.Domain.Entities.Dissertation", "Dissertation")
                        .WithMany("Defenses")
                        .HasForeignKey("DissertationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dissertation");
                });

            modelBuilder.Entity("DissCouncil.Domain.Entities.Dissertation", b =>
                {
                    b.HasOne("DissCouncil.Domain.Entities.Applicant", "Applicant")
                        .WithMany("Dissertations")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("DissCouncil.Domain.Entities.Applicant", b =>
                {
                    b.Navigation("Dissertations");
                });

            modelBuilder.Entity("DissCouncil.Domain.Entities.Dissertation", b =>
                {
                    b.Navigation("Defenses");
                });
#pragma warning restore 612, 618
        }
    }
}
